### ISSUE TITLE
Calibration Process.

### ISSUE THREAD

**Issue by bohunter11** [uChip/VoltageReferenceProgrammable#1]
I have no issues other than this is the only way I knew how to get in contact with you.
I'm looking trough the code and can't wrap my head around the offset correction factor
process. If you could help me I would be very grateful. The pdf file talks about rle but
I don't see where this is being done.

Thank you,
Bo Hunter
email is
bhunter
at
hunterserver
.com

**Comment by uChip** [comment]
Responded with my email.

**Comment by bohunter11** [comment]
I can’t quite make it to 4.096, the 500 ohm trimmer won’t get me there.
This is with fluke 8808a. and I used 1% for R3,4,5. What do you suggest?

Thank You
Bo Hunter
